const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1D4ED8",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E40AF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#EA580C",
    warningForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    surface: "#FFFFFF",
    surfaceElevated: "#F8FAFC",
  },
  dark: {
    text: "#F1F5F9",
    tint: "#3B82F6",
    background: "#0F172A",
    foreground: "#F1F5F9",
    card: "#1E293B",
    cardForeground: "#F1F5F9",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#93C5FD",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#1E3A5F",
    accentForeground: "#93C5FD",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F97316",
    warningForeground: "#FFFFFF",
    border: "#334155",
    input: "#334155",
    surface: "#1E293B",
    surfaceElevated: "#0F172A",
  },
  radius: 16,
};

export default colors;
